### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by liusanchuan** [ROBOTIS-GIT/turtlebot3_manipulation#14]
while i launch ` ROS_NAMESPACE=om_with_tb3 roslaunch turtlebot3_bringup turtlebot3_robot.launch multi_robot_name:=om_with_tb3 set_lidar_frame_id:=om_with_tb3/base_scan` 
there is a warn occur, and i want know what the firmware and the software represent?
```
[ WARN] [1557021239.746816542]: This firmware(v2.0.0) isn't compatible with this software (v1.1.0)
[ WARN] [1557021239.747097329]: You can find how to update its in `FAQ` section(turtlebot3.robotis.com)
```

**Comment by JaehyunShim** [comment]
@liusanchuan 

As the warning says, refer to the following link and update the firmware. 
(http://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#faq)

Regards,
Ryan

**Comment by liusanchuan** [comment]
i did as the FAQ say ,but problem still exit 
[ WARN] [1557021239.746816542]: This firmware(v2.0.0) isn't compatible with this software (v1.1.0)

**Comment by JaehyunShim** [comment]
@liusanchuan 

Update the software and see if it works. Check out the link below.
(http://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#how-to-update-software)

Regards,
Ryan

**Comment by JaehyunShim** [comment]
As there have been no updates on this issue, I am closing this issue.

Ryan
