### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by ahj123** [ROBOTIS-GIT/turtlebot3_manipulation#18]
I am working on TB3 and OM together. Only with TB3 all examples worked very well. However, there happens problem  in opencr firmware upgrade for TB3 with OM. 

1. ttyACM0 disappeared in rebooting after opencr firmware upgrade. 
So I reinstall SBC and reinstall firmware many times in recovery mode. 

2. I did run basic teleoperation example. There was communication probelm and the ros told me some version mismatch problem. 

3. Still example of TB3 are working very well after firmware recovery. 

How can I do it?

**Comment by JaehyunShim** [comment]
Duplicate of https://github.com/ROBOTIS-GIT/open_manipulator_with_tb3/issues/21#issuecomment-586067820
