### ISSUE TITLE
I suggest to modify the map.pgm file.

### ISSUE THREAD

**Issue by minwoominwoominwoo7** [ROBOTIS-GIT/turtlebot3_manipulation#20]
hello :)
Currently the map.pgm file is in absolute path. 
I think it looks good to change to relative path like below.

The file is https://github.com/ROBOTIS-GIT/open_manipulator_with_tb3/blob/master/open_manipulator_with_tb3_tools/maps/map.pgm

---modified point
image: /home/darby/maps/turtlebot3_rooms/map.pgm  
-> image: ./map.pgm

**Comment by JaehyunShim** [comment]
Thank you for the comment. I will discuss it with the team and make modifications if needed. 
Ryan
