### ISSUE TITLE
cannot use the python API to control the manipulator

### ISSUE THREAD

**Issue by flieed** [ROBOTIS-GIT/turtlebot3_manipulation#40]
I successfully realized kinematics.yaml by configuring kinematics.yaml, but I still couldn't control it with the python API. Thank you for your valuable time to help me
`       
        arm = moveit_commander.MoveGroupCommander('arm')        
        end_effector_link = arm.get_end_effector_link()                   
        reference_frame = 'base_link'
        arm.set_pose_reference_frame(reference_frame)
                
     
        arm.allow_replanning(True)
        
        arm.set_goal_position_tolerance(0.001)
        arm.set_goal_orientation_tolerance(0.001)
        arm.shift_pose_target(2, 0.05, end_effector_link)
        arm.go()
	print ('end')
        rospy.sleep(1)`

**Comment by JaehyunShim** [comment]
@flieed 

Hi. As your question is more about the usage of MoveIt APIs rather than our robot platform, please leave your question at the [link](https://github.com/ros-planning/moveit/issues).

Regards,
Ryan
