### ISSUE TITLE
Manipulation of Turtlebot3 with Open Manipulator. joint state error

### ISSUE THREAD

**Issue by jellegroothuis** [ROBOTIS-GIT/turtlebot3_manipulation#44]
I did follow emanual in Manipulation of Turtlebot3 to setup Open Manipulator with Turtlebot3 Waffle.
But I face problems when follow emanual to run.

On Remote PC:
roslaunch turtlebot3_bringup turtlebot3_robot.launch, No problem
roslaunch turtlebot3_manipulation_bringup turtlebot3_manipulation_bringup.launch, No problem
roslaunch turtlebot3_manipulation_moveit_config move_group.launch, I got a warning:
![Screenshot from 2022-06-01 09-46-25](https://user-images.githubusercontent.com/106654624/171354830-4a324f33-c59b-48a2-b0af-db5c39be619a.png)

does anyone know what i'm doing wrong? or how can I fix this problem? my knowledge of ROS is currently not good enough to remedy this.

**Comment by ROBOTIS-Will** [comment]
Hi @jellegroothuis 
Which ROS do you use?
You should run the bringup command on your Turtlebot3 SBC(Raspberry Pi), not on your Remote PC
```bash
$ roslaunch turtlebot3_bringup turtlebot3_robot.launch
```

**Comment by jellegroothuis** [comment]
the problem is solved. the wrong software was on the openCR.

turtlebot3 with openmanipulator was needed while turtlebot 3 core was in the manual.

**Comment by goekce** [comment]
@jellegroothuis  please close the issue if your problem is solved.
