### ISSUE TITLE
Turtlebot3 with manipulator issue

### ISSUE THREAD

**Issue by BENBEY-I** [ROBOTIS-GIT/turtlebot3_manipulation#46]
I'm working with turtlebot3 waffle pi with open manipulator, i'm using ROS kinetic.
I did follow emanual in Manipulation of Turtlebot3 to setup Open Manipulator with Turtlebot3 Waffle_pi.
when i upload the firmware on SBC the arm didn't move to the initial pose even though it's was uploaded successfully

![image](https://user-images.githubusercontent.com/105348283/177180377-f4e30a46-e339-4feb-b9ab-72a70ae468c5.png)

and when i launch the bringup launch file i get this error 

![image](https://user-images.githubusercontent.com/105348283/177182526-e59c8176-75df-46c6-b526-de9839c44e5e.png)

I tried the other method using Arduino IDE i get the same results (upload successfully but no motion)

I used the Dynamixel wizard 2.0 to check the connect to the motors but it couldn't detect the motors 

my question : is there any way to check the status of the motors ?

**Comment by sunghowoo** [comment]
Sorry for the late response. Since ROS Kinetic has reached its end of life, please try using ROS Noetic or ROS2 Humble and feel free to raise the issue again if it persists.
