### ISSUE TITLE
Control the TB3 base with the trajectory of MoveIt?

### ISSUE THREAD

**Issue by MikeHallettUK** [ROBOTIS-GIT/turtlebot3_manipulation#48]
As described here... https://answers.ros.org/question/284792/control-the-base-with-the-trajectory-of-moveit/

... can you develop a [ros_control](http://wiki.ros.org/action/fullsearch/ros_control?action=fullsearch&context=180&value=linkto%3A%22ros_control%22) package to include the TB3 base as link joint1 of the manipulator, so that the arm can at least rotate, using the angular velocity and imu yaw feedback into a joint_position_controller, so that Move-it can include this base rotation into its kinematic planning and execution ?

... or at least give me some guidance on how to do this ?

Thanks

Mike

**Comment by sunghowoo** [comment]
1. Modify URDF: Add a virtual joint in the URDF to connect the TurtleBot3 base to the manipulator's first joint (e.g., base_to_joint1). Make it a continuous joint to represent the base rotation.

2. Create Joint Controller: In the ros_controllers.yaml file, define a joint_position_controller for the base's rotation using base_to_joint1.

3. IMU Feedback: Use the IMU’s yaw data as feedback for controlling the base rotation in the hardware interface.

4. Update MoveIt: Add the virtual base joint to the MoveIt configuration and include it in the kinematic chain for planning.

Sorry for the late response, this question is beyond our product specifications, so I will close it.
