### ISSUE TITLE
Failure with ros2 launch turtlebot3_manipulation_bringup hardware.launch.py

### ISSUE THREAD

**Issue by UniBot50** [ROBOTIS-GIT/turtlebot3_manipulation#51]
I'm working with turtlebot 3 waffle and the OpenMANIPULATOR-X mounted in top. I installed everything as described in the e-manual. But when I want to launch the bring up with <ros2 launch turtlebot3_manipulation_bringup hardware.launch.py> I get the following error message:  

![Screenshot from 2022-12-09 14-14-05](https://user-images.githubusercontent.com/120188158/206712361-b80a1db0-fd73-44e1-b377-13a4767a45c3.png)
  

Somebody what I can do about that?

**Comment by JBVAkshaya** [comment]
I am running into the same issue. Were you able to fix this issue? There is a high possibility that as of now this repository is not compatible with ROS 2. From the wiki, the latest compatibility seems to be with ROS Melodic + Ubuntu Bionic.

**Comment by wecacuee** [comment]
[hardware.launch.py](https://github.com/ROBOTIS-GIT/turtlebot3_manipulation/blob/foxy-devel/turtlebot3_manipulation_bringup/launch/hardware.launch.py) includes [base.launch.py](https://github.com/ROBOTIS-GIT/turtlebot3_manipulation/blob/foxy-devel/turtlebot3_manipulation_bringup/launch/base.launch.py) which needs `FindExecutable(name='xacro')`. 

Make sure ros-foxy-xacro is installed
```
sudo apt install ros-foxy-xacro
```

**Comment by UniBot50** [comment]
This was it, thank you very much!
