### ISSUE TITLE
Issue with ros2 launch turtlebot3_manipulation_bringup hardware.launch.py

### ISSUE THREAD

**Issue by UniBot50** [ROBOTIS-GIT/turtlebot3_manipulation#55]
Hello,
I'm currently working with the Turtlebot3 in combination with the OpenMANIPULATOR-X and ROS2 foxy. I installed as per the e-manual. However, when I try to do ros2 launch, it doesn't work. I think it might be the ROS2 control manager. does anyone have a solution?

<pre><font color="#4E9A06"><b>ubuntu@ubuntu</b></font>:<font color="#3465A4"><b>~/turtlebot3_ws</b></font>$ ros2 launch turtlebot3_manipulation_bringup hardware.launch.py
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2023-02-16-13-43-06-199808-ubuntu-11712
[INFO] [launch]: Default logging verbosity is set to INFO
/opt/ros/foxy/share/hls_lfcd_lds_driver/launch/hlds_laser.launch.py:46: UserWarning: The parameter &apos;node_executable&apos; is deprecated, use &apos;executable&apos; instead
  Node(
/opt/ros/foxy/share/hls_lfcd_lds_driver/launch/hlds_laser.launch.py:46: UserWarning: The parameter &apos;node_name&apos; is deprecated, use &apos;name&apos; instead
  Node(
[INFO] [robot_state_publisher-1]: process started with pid [11716]
[INFO] [ros2_control_node-2]: process started with pid [11718]
[INFO] [spawner.py-3]: process started with pid [11720]
[INFO] [spawner.py-4]: process started with pid [11722]
[INFO] [spawner.py-5]: process started with pid [11724]
[INFO] [spawner.py-6]: process started with pid [11727]
[INFO] [spawner.py-7]: process started with pid [11736]
[INFO] [hlds_laser_publisher-8]: process started with pid [11746]
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link base_link had 8 children
[robot_state_publisher-1] Link link1 had 1 children
[robot_state_publisher-1] Link link2 had 1 children
[robot_state_publisher-1] Link link3 had 1 children
[robot_state_publisher-1] Link link4 had 1 children
[robot_state_publisher-1] Link link5 had 3 children
[robot_state_publisher-1] Link end_effector_link had 0 children
[robot_state_publisher-1] Link gripper_left_link had 0 children
[robot_state_publisher-1] Link gripper_right_link had 0 children
[robot_state_publisher-1] Link camera_link had 1 children
[robot_state_publisher-1] Link camera_rgb_frame had 1 children
[robot_state_publisher-1] Link camera_rgb_optical_frame had 0 children
[robot_state_publisher-1] Link caster_back_left_link had 0 children
[robot_state_publisher-1] Link caster_back_right_link had 0 children
[robot_state_publisher-1] Link imu_link had 0 children
[robot_state_publisher-1] Link base_scan had 0 children
[robot_state_publisher-1] Link wheel_left_link had 0 children
[robot_state_publisher-1] Link wheel_right_link had 0 children
[robot_state_publisher-1] [INFO] [1676554987.994990553] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-1] [INFO] [1676554987.995765581] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1676554987.995904904] [robot_state_publisher]: got segment base_scan
[robot_state_publisher-1] [INFO] [1676554987.995944906] [robot_state_publisher]: got segment camera_link
[robot_state_publisher-1] [INFO] [1676554987.995973427] [robot_state_publisher]: got segment camera_rgb_frame
[robot_state_publisher-1] [INFO] [1676554987.996002354] [robot_state_publisher]: got segment camera_rgb_optical_frame
[robot_state_publisher-1] [INFO] [1676554987.996032671] [robot_state_publisher]: got segment caster_back_left_link
[robot_state_publisher-1] [INFO] [1676554987.996063395] [robot_state_publisher]: got segment caster_back_right_link
[robot_state_publisher-1] [INFO] [1676554987.996092526] [robot_state_publisher]: got segment end_effector_link
[robot_state_publisher-1] [INFO] [1676554987.996120343] [robot_state_publisher]: got segment gripper_left_link
[robot_state_publisher-1] [INFO] [1676554987.996263222] [robot_state_publisher]: got segment gripper_right_link
[robot_state_publisher-1] [INFO] [1676554987.996312243] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-1] [INFO] [1676554987.996344745] [robot_state_publisher]: got segment link1
[robot_state_publisher-1] [INFO] [1676554987.996372876] [robot_state_publisher]: got segment link2
[robot_state_publisher-1] [INFO] [1676554987.996399952] [robot_state_publisher]: got segment link3
[robot_state_publisher-1] [INFO] [1676554987.996426509] [robot_state_publisher]: got segment link4
[robot_state_publisher-1] [INFO] [1676554987.996453307] [robot_state_publisher]: got segment link5
[robot_state_publisher-1] [INFO] [1676554987.996480179] [robot_state_publisher]: got segment wheel_left_link
[robot_state_publisher-1] [INFO] [1676554987.996507810] [robot_state_publisher]: got segment wheel_right_link
[ros2_control_node-2] [INFO] [1676554988.182059694] [turtlebot3_manipulation]: Succeeded to open port
[ros2_control_node-2] [INFO] [1676554988.187762498] [turtlebot3_manipulation]: Succeeded to set baudrate
[ros2_control_node-2] [INFO] [1676554988.188493726] [turtlebot3_manipulation]: OpenCR Model Number 20480
[ros2_control_node-2] [INFO] [1676554988.191427217] [turtlebot3_manipulation]: Connected manipulator
[ros2_control_node-2] [INFO] [1676554988.205440832] [turtlebot3_manipulation]: Connected wheels
[ros2_control_node-2] [INFO] [1676554988.206352534] [turtlebot3_manipulation]: Ready for start
[ros2_control_node-2] [INFO] [1676554988.207437414] [turtlebot3_manipulation]: Wait for IMU re-calibration
[ros2_control_node-2] <font color="#CC0000"><b>[ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!</b></font>
[hlds_laser_publisher-8] [INFO] [1676554988.250272548] [hlds_laser_publisher]: Init hlds_laser_publisher Node Main
[hlds_laser_publisher-8] [INFO] [1676554988.250893844] [hlds_laser_publisher]: port : /dev/ttyUSB0 frame_id : base_scan
[spawner.py-6] [INFO] [1676554989.870867463] [spawner_arm_controller]: Waiting for /controller_manager services
[spawner.py-4] Traceback (most recent call last):
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 46, in import_type_support
[spawner.py-4]     return importlib.import_module(module_name, package=pkg_name)
[spawner.py-4]   File &quot;/usr/lib/python3.8/importlib/__init__.py&quot;, line 127, in import_module
[spawner.py-4]     return _bootstrap._gcd_import(name[level:], package, level)
[spawner.py-4]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1014, in _gcd_import
[spawner.py-4]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 991, in _find_and_load
[spawner.py-4]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 975, in _find_and_load_unlocked
[spawner.py-4]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 657, in _load_unlocked
[spawner.py-4]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 556, in module_from_spec
[spawner.py-4]   File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1166, in create_module
[spawner.py-4]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed
[spawner.py-4] ImportError: /opt/ros/foxy/lib/libcontroller_manager_msgs__rosidl_generator_c.so: undefined symbol: builtin_interfaces__msg__Duration__are_equal
[spawner.py-4] 
[spawner.py-4] During handling of the above exception, another exception occurred:
[spawner.py-4] 
[spawner.py-4] Traceback (most recent call last):
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 204, in &lt;module&gt;
[spawner.py-4]     sys.exit(main())
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 123, in main
[spawner.py-4]     if is_controller_loaded(node, controller_manager_name, controller_name):
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 65, in is_controller_loaded
[spawner.py-4]     controllers = list_controllers(node, controller_manager).controller
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 49, in list_controllers
[spawner.py-4]     return service_caller(node, f&apos;{controller_manager_name}/list_controllers&apos;,
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 23, in service_caller
[spawner.py-4]     cli = node.create_client(service_type, service_name)
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/node.py&quot;, line 1248, in create_client
[spawner.py-4]     check_for_type_support(srv_type)
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/type_support.py&quot;, line 29, in check_for_type_support
[spawner.py-4]     msg_type.__class__.__import_type_support__()
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager_msgs/srv/_list_controllers.py&quot;, line 250, in __import_type_support__
[spawner.py-4]     module = import_type_support(&apos;controller_manager_msgs&apos;)
[spawner.py-4]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 48, in import_type_support
[spawner.py-4]     raise UnsupportedTypeSupport(pkg_name)
[spawner.py-4] rosidl_generator_py.import_type_support_impl.UnsupportedTypeSupport: Could not import &apos;rosidl_typesupport_c&apos; for package &apos;controller_manager_msgs&apos;
[spawner.py-3] Traceback (most recent call last):
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 46, in import_type_support
[spawner.py-3]     return importlib.import_module(module_name, package=pkg_name)
[spawner.py-3]   File &quot;/usr/lib/python3.8/importlib/__init__.py&quot;, line 127, in import_module
[spawner.py-3]     return _bootstrap._gcd_import(name[level:], package, level)
[spawner.py-3]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1014, in _gcd_import
[spawner.py-3]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 991, in _find_and_load
[spawner.py-3]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 975, in _find_and_load_unlocked
[spawner.py-3]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 657, in _load_unlocked
[spawner.py-3]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 556, in module_from_spec
[spawner.py-3]   File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1166, in create_module
[spawner.py-3]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed
[spawner.py-3] ImportError: /opt/ros/foxy/lib/libcontroller_manager_msgs__rosidl_generator_c.so: undefined symbol: builtin_interfaces__msg__Duration__are_equal
[spawner.py-3] 
[spawner.py-3] During handling of the above exception, another exception occurred:
[spawner.py-3] 
[spawner.py-3] Traceback (most recent call last):
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 204, in &lt;module&gt;
[spawner.py-3]     sys.exit(main())
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 123, in main
[spawner.py-3]     if is_controller_loaded(node, controller_manager_name, controller_name):
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 65, in is_controller_loaded
[spawner.py-3]     controllers = list_controllers(node, controller_manager).controller
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 49, in list_controllers
[spawner.py-3]     return service_caller(node, f&apos;{controller_manager_name}/list_controllers&apos;,
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 23, in service_caller
[spawner.py-3]     cli = node.create_client(service_type, service_name)
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/node.py&quot;, line 1248, in create_client
[spawner.py-3]     check_for_type_support(srv_type)
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/type_support.py&quot;, line 29, in check_for_type_support
[spawner.py-3]     msg_type.__class__.__import_type_support__()
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager_msgs/srv/_list_controllers.py&quot;, line 250, in __import_type_support__
[spawner.py-3]     module = import_type_support(&apos;controller_manager_msgs&apos;)
[spawner.py-3]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 48, in import_type_support
[spawner.py-3]     raise UnsupportedTypeSupport(pkg_name)
[spawner.py-3] rosidl_generator_py.import_type_support_impl.UnsupportedTypeSupport: Could not import &apos;rosidl_typesupport_c&apos; for package &apos;controller_manager_msgs&apos;
[spawner.py-5] Traceback (most recent call last):
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 46, in import_type_support
[spawner.py-5]     return importlib.import_module(module_name, package=pkg_name)
[spawner.py-5]   File &quot;/usr/lib/python3.8/importlib/__init__.py&quot;, line 127, in import_module
[spawner.py-5]     return _bootstrap._gcd_import(name[level:], package, level)
[spawner.py-5]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1014, in _gcd_import
[spawner.py-5]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 991, in _find_and_load
[spawner.py-5]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 975, in _find_and_load_unlocked
[spawner.py-5]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 657, in _load_unlocked
[spawner.py-5]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 556, in module_from_spec
[spawner.py-5]   File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1166, in create_module
[spawner.py-5]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed
[spawner.py-5] ImportError: /opt/ros/foxy/lib/libcontroller_manager_msgs__rosidl_generator_c.so: undefined symbol: builtin_interfaces__msg__Duration__are_equal
[spawner.py-5] 
[spawner.py-5] During handling of the above exception, another exception occurred:
[spawner.py-5] 
[spawner.py-5] Traceback (most recent call last):
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 204, in &lt;module&gt;
[spawner.py-5]     sys.exit(main())
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 123, in main
[spawner.py-5]     if is_controller_loaded(node, controller_manager_name, controller_name):
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 65, in is_controller_loaded
[spawner.py-5]     controllers = list_controllers(node, controller_manager).controller
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 49, in list_controllers
[spawner.py-5]     return service_caller(node, f&apos;{controller_manager_name}/list_controllers&apos;,
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 23, in service_caller
[spawner.py-5]     cli = node.create_client(service_type, service_name)
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/node.py&quot;, line 1248, in create_client
[spawner.py-5]     check_for_type_support(srv_type)
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/type_support.py&quot;, line 29, in check_for_type_support
[spawner.py-5]     msg_type.__class__.__import_type_support__()
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager_msgs/srv/_list_controllers.py&quot;, line 250, in __import_type_support__
[spawner.py-5]     module = import_type_support(&apos;controller_manager_msgs&apos;)
[spawner.py-5]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 48, in import_type_support
[spawner.py-5]     raise UnsupportedTypeSupport(pkg_name)
[spawner.py-5] rosidl_generator_py.import_type_support_impl.UnsupportedTypeSupport: Could not import &apos;rosidl_typesupport_c&apos; for package &apos;controller_manager_msgs&apos;
[spawner.py-7] Traceback (most recent call last):
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 46, in import_type_support
[spawner.py-7]     return importlib.import_module(module_name, package=pkg_name)
[spawner.py-7]   File &quot;/usr/lib/python3.8/importlib/__init__.py&quot;, line 127, in import_module
[spawner.py-7]     return _bootstrap._gcd_import(name[level:], package, level)
[spawner.py-7]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1014, in _gcd_import
[spawner.py-7]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 991, in _find_and_load
[spawner.py-7]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 975, in _find_and_load_unlocked
[spawner.py-7]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 657, in _load_unlocked
[spawner.py-7]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 556, in module_from_spec
[spawner.py-7]   File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1166, in create_module
[spawner.py-7]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed
[spawner.py-7] ImportError: /opt/ros/foxy/lib/libcontroller_manager_msgs__rosidl_generator_c.so: undefined symbol: builtin_interfaces__msg__Duration__are_equal
[spawner.py-7] 
[spawner.py-7] During handling of the above exception, another exception occurred:
[spawner.py-7] 
[spawner.py-7] Traceback (most recent call last):
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 204, in &lt;module&gt;
[spawner.py-7]     sys.exit(main())
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 123, in main
[spawner.py-7]     if is_controller_loaded(node, controller_manager_name, controller_name):
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 65, in is_controller_loaded
[spawner.py-7]     controllers = list_controllers(node, controller_manager).controller
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 49, in list_controllers
[spawner.py-7]     return service_caller(node, f&apos;{controller_manager_name}/list_controllers&apos;,
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 23, in service_caller
[spawner.py-7]     cli = node.create_client(service_type, service_name)
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/node.py&quot;, line 1248, in create_client
[spawner.py-7]     check_for_type_support(srv_type)
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/type_support.py&quot;, line 29, in check_for_type_support
[spawner.py-7]     msg_type.__class__.__import_type_support__()
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager_msgs/srv/_list_controllers.py&quot;, line 250, in __import_type_support__
[spawner.py-7]     module = import_type_support(&apos;controller_manager_msgs&apos;)
[spawner.py-7]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 48, in import_type_support
[spawner.py-7]     raise UnsupportedTypeSupport(pkg_name)
[spawner.py-7] rosidl_generator_py.import_type_support_impl.UnsupportedTypeSupport: Could not import &apos;rosidl_typesupport_c&apos; for package &apos;controller_manager_msgs&apos;
[ERROR] [spawner.py-4]: process has died [pid 11722, exit code 1, cmd &apos;/opt/ros/foxy/lib/controller_manager/spawner.py diff_drive_controller --ros-args&apos;].
[ERROR] [spawner.py-5]: process has died [pid 11724, exit code 1, cmd &apos;/opt/ros/foxy/lib/controller_manager/spawner.py imu_broadcaster --ros-args&apos;].
[ERROR] [spawner.py-3]: process has died [pid 11720, exit code 1, cmd &apos;/opt/ros/foxy/lib/controller_manager/spawner.py joint_state_broadcaster --ros-args&apos;].
[ERROR] [spawner.py-7]: process has died [pid 11736, exit code 1, cmd &apos;/opt/ros/foxy/lib/controller_manager/spawner.py gripper_controller --ros-args&apos;].
[ros2_control_node-2] [INFO] [1676554991.242334495] [turtlebot3_manipulation]: Joints and wheels torque ON
[ros2_control_node-2] [INFO] [1676554991.255019905] [turtlebot3_manipulation]: Set profile acceleration and velocity to joints
[ros2_control_node-2] [INFO] [1676554991.293044467] [turtlebot3_manipulation]: Set profile acceleration and velocity to gripper
[ros2_control_node-2] [INFO] [1676554991.318033190] [turtlebot3_manipulation]: Set goal current value to gripper
[ros2_control_node-2] [INFO] [1676554991.337026924] [turtlebot3_manipulation]: System starting
[ros2_control_node-2] [INFO] [1676554991.360502501] [controller_manager]: update rate is 100 Hz
[ros2_control_node-2] [INFO] [1676554991.371834755] [turtlebot3_manipulation]: Start to read wheels and manipulator states
[ros2_control_node-2] [INFO] [1676554991.378533084] [turtlebot3_manipulation]: Start to write wheels and manipulator commands
[spawner.py-6] Traceback (most recent call last):
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 46, in import_type_support
[spawner.py-6]     return importlib.import_module(module_name, package=pkg_name)
[spawner.py-6]   File &quot;/usr/lib/python3.8/importlib/__init__.py&quot;, line 127, in import_module
[spawner.py-6]     return _bootstrap._gcd_import(name[level:], package, level)
[spawner.py-6]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1014, in _gcd_import
[spawner.py-6]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 991, in _find_and_load
[spawner.py-6]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 975, in _find_and_load_unlocked
[spawner.py-6]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 657, in _load_unlocked
[spawner.py-6]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 556, in module_from_spec
[spawner.py-6]   File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1166, in create_module
[spawner.py-6]   File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed
[spawner.py-6] ImportError: /opt/ros/foxy/lib/libcontroller_manager_msgs__rosidl_generator_c.so: undefined symbol: builtin_interfaces__msg__Duration__are_equal
[spawner.py-6] 
[spawner.py-6] During handling of the above exception, another exception occurred:
[spawner.py-6] 
[spawner.py-6] Traceback (most recent call last):
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 204, in &lt;module&gt;
[spawner.py-6]     sys.exit(main())
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 123, in main
[spawner.py-6]     if is_controller_loaded(node, controller_manager_name, controller_name):
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/controller_manager/spawner.py&quot;, line 65, in is_controller_loaded
[spawner.py-6]     controllers = list_controllers(node, controller_manager).controller
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 49, in list_controllers
[spawner.py-6]     return service_caller(node, f&apos;{controller_manager_name}/list_controllers&apos;,
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager/controller_manager_services.py&quot;, line 23, in service_caller
[spawner.py-6]     cli = node.create_client(service_type, service_name)
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/node.py&quot;, line 1248, in create_client
[spawner.py-6]     check_for_type_support(srv_type)
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rclpy/type_support.py&quot;, line 29, in check_for_type_support
[spawner.py-6]     msg_type.__class__.__import_type_support__()
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/controller_manager_msgs/srv/_list_controllers.py&quot;, line 250, in __import_type_support__
[spawner.py-6]     module = import_type_support(&apos;controller_manager_msgs&apos;)
[spawner.py-6]   File &quot;/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py&quot;, line 48, in import_type_support
[spawner.py-6]     raise UnsupportedTypeSupport(pkg_name)
[spawner.py-6] rosidl_generator_py.import_type_support_impl.UnsupportedTypeSupport: Could not import &apos;rosidl_typesupport_c&apos; for package &apos;controller_manager_msgs&apos;
[ERROR] [spawner.py-6]: process has died [pid 11727, exit code 1, cmd &apos;/opt/ros/foxy/lib/controller_manager/spawner.py arm_controller --ros-args&apos;].
</pre>

**Comment by lmendyk** [comment]
I have the same problem (slightly different setup - I used “hotfix-humble-tb3-omx” adapted to galactic ROS2 installation – works good for simulations, but for real Turtlebot3 Raspberry PI 4 with Open Manipulation   I get exactly the same result )

**Comment by lmendyk** [comment]
I have solved the problem (a sort of), the issue seems to be with the opencr_baud_rate. it was set to 1000000 and I change it to 115200 (which was a value I found int turtlebot3 urdf  model). And the robot starts .  I can control the robot via MoveIt, the robot arm makes movement but NOT smoothly and the initial position is not proper one.  Probably the baud rate should be  tune better.  Will try to improve it

**Comment by UniBot50** [comment]
Hey Imendyk, thanks for your reply. I solved the problem on my side by just doing a "sudo apt-get update" and a  "sudo apt-get dist-upgrade" after all installations on the Raspberry. Afterwards the "ros2 launch turtlebot3_manipulation_bringup hardware.launch.py" started normally. But now I am still struggling with controlling the real OpenManipulator. Can you explain me how you controlled the arm? Like what commands did you use and did you control it via the RViz Gui? Or how did you use MoveIt?

Greetings

**Comment by lmendyk** [comment]
I have used MoveIt2 and rviz GUI with MotionPlanning\Planning plugin -so I could request the planning (for example "radom valid position" for "Goal state"  - then "execute".  But the effect is very jerked movements of the arm :(

To launch I used commands from 
https://emanual.robotis.com/docs/en/platform/turtlebot3/manipulation/#operate-the-actual-openmanipulator  ("Foxy instructions")

 `ros2 launch turtlebot3_manipulation_moveit_config moveit_core.launch.py`

It looks to me that the version for Ros2 is far from complete, for example I have notices in ompl_planning.yaml still having  references to "panda_arm" which looks as copy-pased examples not yet adapted tu tb3 and OM  so that is why I have asked for info about roadmap #57

**Comment by sunghowoo** [comment]
It seems the initial issue has been resolved, so I will go ahead and close this issue.
