### ISSUE TITLE
Turtlebot3: Open Manipulator Bringup Fails: DynamixelSDKWrapper: No status packet! Proces died: stack smashing detected.

### ISSUE THREAD

**Issue by perrombouts2322** [ROBOTIS-GIT/turtlebot3_manipulation#58]
Turtlebot3: Open Manipulator: bringup fails: ERROR from Dynamixels SDKWrapper : No status packet found + proces dies: stack smashing detected.

- Ros 2 Humble
- Raspberry Pi 4
- Ubuntu 22.04 
- OPEN CR 1.0
- Servo's: xm430-w350-t

Hello, me and my student group from UPV Valencia are following the ROBOTIS E-Manuel for the Turtlebot3: Open Manipualtor. We are following the steps issued for Foxy because Humble is not available.
https://emanual.robotis.com/docs/en/platform/turtlebot3/manipulation/#turtlebot3-with-openmanipulator

We are currently stuck at step 7.5 (Bringup).

We took these premature steps:

**SOFTWARE SETUP:** (humble instead of foxy installed)

  $ sudo apt install ros-humble-dynamixel-sdk ros-humble-ros2-control ros-humble-ros2-controllers ros-humble-gripper-controllers ros-humble-moveit
  $ cd ~/turtlebot3_ws/src/
  $ git clone -b humble-devel https://github.com/ROBOTIS-GIT/turtlebot3_manipulation.git
  $ cd ~/turtlebot3_ws && colcon build --symlink-install

**OPEN CR FIRMWARE SETUP**

$ export OPENCR_PORT=/dev/ttyACM0
$ export OPENCR_MODEL=turtlebot3_manipulation
$ rm -rf ./opencr_update.tar.bz2
$ wget https://github.com/ROBOTIS-GIT/OpenCR-Binaries/raw/master/turtlebot3/ROS2/latest/opencr_update.tar.bz2
$ tar -xvf opencr_update.tar.bz2
$ cd ./opencr_update
$ ./update.sh $OPENCR_PORT $OPENCR_MODEL.opencr

Then when we try to launch the hardware bringup:

$ ros2 launch turtlebot3_manipulation_bringup hardware.launch.py

We get multiple errors stating:

 [ros2-control-node-1]  [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!

Later the proces dies stating:

**stack smashing detected**

I will upload screenshots taken stating the full output code:

![Code1_Issue](https://user-images.githubusercontent.com/129193662/228828922-d2e91c99-b2f8-4b48-83d8-63fca31e61d5.jpg)
![Code2_Issue](https://user-images.githubusercontent.com/129193662/228828920-24ec8d22-8daa-40b3-93ed-61d823c2d9c5.jpg)

We as a group think it has to do with an incompatible firmware version on our OPEN CR board. Can anyone please help us resolve this issue or give an indication what the problem might be? Thanks!

**Comment by perrombouts2322** [comment]
We are using a Waffle Pi.
Any help would be appreciated @ROBOTIS-Will

**Comment by ozanaki** [comment]
**Exactly same issue (ubuntu 20, ros2 foxy, waffle pi with manipulator ):**

ubuntu@wafflepi:~$ ros2 launch turtlebot3_manipulation_bringup hardware.launch.py
[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2023-06-02-12-00-40-146522-wafflepi-3470
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [3474]
[INFO] [ros2_control_node-2]: process started with pid [3476]
[INFO] [spawner.py-3]: process started with pid [3478]
[INFO] [spawner.py-4]: process started with pid [3480]
[INFO] [spawner.py-5]: process started with pid [3482]
[INFO] [spawner.py-6]: process started with pid [3485]
[INFO] [spawner.py-7]: process started with pid [3495]
[INFO] [ld08_driver-8]: process started with pid [3498]
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link base_link had 8 children
[robot_state_publisher-1] Link link1 had 1 children
[robot_state_publisher-1] Link link2 had 1 children
[robot_state_publisher-1] Link link3 had 1 children
[robot_state_publisher-1] Link link4 had 1 children
[robot_state_publisher-1] Link link5 had 3 children
[robot_state_publisher-1] Link end_effector_link had 0 children
[robot_state_publisher-1] Link gripper_left_link had 0 children
[robot_state_publisher-1] Link gripper_right_link had 0 children
[robot_state_publisher-1] Link camera_link had 1 children
[robot_state_publisher-1] Link camera_rgb_frame had 1 children
[robot_state_publisher-1] Link camera_rgb_optical_frame had 0 children
[robot_state_publisher-1] Link caster_back_left_link had 0 children
[robot_state_publisher-1] Link caster_back_right_link had 0 children
[robot_state_publisher-1] Link imu_link had 0 children
[robot_state_publisher-1] Link base_scan had 0 children
[robot_state_publisher-1] Link wheel_left_link had 0 children
[robot_state_publisher-1] Link wheel_right_link had 0 children
[robot_state_publisher-1] [INFO] [1685707242.042635204] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-1] [INFO] [1685707242.045494339] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1685707242.045625744] [robot_state_publisher]: got segment base_scan
[robot_state_publisher-1] [INFO] [1685707242.045670947] [robot_state_publisher]: got segment camera_link
[robot_state_publisher-1] [INFO] [1685707242.045708965] [robot_state_publisher]: got segment camera_rgb_frame
[robot_state_publisher-1] [INFO] [1685707242.045741520] [robot_state_publisher]: got segment camera_rgb_optical_frame
[robot_state_publisher-1] [INFO] [1685707242.045771779] [robot_state_publisher]: got segment caster_back_left_link
[robot_state_publisher-1] [INFO] [1685707242.045803167] [robot_state_publisher]: got segment caster_back_right_link
[robot_state_publisher-1] [INFO] [1685707242.045833463] [robot_state_publisher]: got segment end_effector_link
[robot_state_publisher-1] [INFO] [1685707242.045862796] [robot_state_publisher]: got segment gripper_left_link
[robot_state_publisher-1] [INFO] [1685707242.045893091] [robot_state_publisher]: got segment gripper_right_link
[robot_state_publisher-1] [INFO] [1685707242.045922832] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-1] [INFO] [1685707242.045951683] [robot_state_publisher]: got segment link1
[robot_state_publisher-1] [INFO] [1685707242.045986590] [robot_state_publisher]: got segment link2
[robot_state_publisher-1] [INFO] [1685707242.046017830] [robot_state_publisher]: got segment link3
[robot_state_publisher-1] [INFO] [1685707242.046046607] [robot_state_publisher]: got segment link4
[robot_state_publisher-1] [INFO] [1685707242.046076996] [robot_state_publisher]: got segment link5
[robot_state_publisher-1] [INFO] [1685707242.046105643] [robot_state_publisher]: got segment wheel_left_link
[robot_state_publisher-1] [INFO] [1685707242.046136087] [robot_state_publisher]: got segment wheel_right_link
[ros2_control_node-2] [INFO] [1685707242.248574918] [turtlebot3_manipulation]: Succeeded to open port
[ros2_control_node-2] [INFO] [1685707242.256281506] [turtlebot3_manipulation]: Succeeded to set baudrate
[ros2_control_node-2] [INFO] [1685707242.260948239] [turtlebot3_manipulation]: OpenCR Model Number 20480
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [INFO] [1685707242.295394063] [turtlebot3_manipulation]: Connected manipulator
[ros2_control_node-2] [INFO] [1685707242.296914906] [turtlebot3_manipulation]: Connected wheels
[ros2_control_node-2] [INFO] [1685707242.297786373] [turtlebot3_manipulation]: Ready for start
[ros2_control_node-2] [INFO] [1685707242.331958701] [turtlebot3_manipulation]: Wait for IMU re-calibration
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ld08_driver-8] /dev/ttyUSB0    CP2102 USB to UART Bridge Controller
[ld08_driver-8] /dev/ttyACM0    OpenCR Virtual ComPort in FS Mode
[ld08_driver-8] FOUND LDS-02
[ld08_driver-8] LDS-02 started successfully
[spawner.py-3] [INFO] [1685707243.541086839] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner.py-7] [INFO] [1685707244.079948936] [spawner_gripper_controller]: Waiting for /controller_manager services
[ros2_control_node-2] [INFO] [1685707245.366706458] [turtlebot3_manipulation]: Joints and wheels torque ON
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [INFO] [1685707245.418298778] [turtlebot3_manipulation]: Set profile acceleration and velocity to joints
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [INFO] [1685707245.489296815] [turtlebot3_manipulation]: Set profile acceleration and velocity to gripper
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [INFO] [1685707245.560288777] [turtlebot3_manipulation]: Set goal current value to gripper
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [INFO] [1685707245.596314110] [turtlebot3_manipulation]: System starting
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [INFO] [1685707245.677342546] [controller_manager]: update rate is 100 Hz
[ros2_control_node-2] [INFO] [1685707245.686191280] [controller_manager]: Loading controller 'arm_controller'
[ros2_control_node-2] [INFO] [1685707245.687851547] [turtlebot3_manipulation]: Start to read wheels and manipulator states
[ros2_control_node-2] [INFO] [1685707245.707218986] [turtlebot3_manipulation]: Start to write wheels and manipulator commands
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [ERROR] [1685707245.774622586] [turtlebot3_manipulation]: Can't control wheels
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [ERROR] [DynamixelSDKWrapper] [TxRxResult] There is no status packet!
[ros2_control_node-2] [INFO] [1685707245.863331090] [controller_manager]: Loading controller 'gripper_controller'
[ros2_control_node-2] *** stack smashing detected ***: terminated
[spawner.py-6] [INFO] [1685707245.935698918] [spawner_arm_controller]: Loaded arm_controller
[ERROR] [ros2_control_node-2]: process has died [pid 3476, exit code -6, cmd '/opt/ros/foxy/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_31e0hl2w --params-file /home/ubuntu/turtlebot3_ws/install/turtlebot3_manipulation_bringup/share/turtlebot3_manipulation_bringup/config/hardware_controller_manager.yaml -r ~/cmd_vel_unstamped:=cmd_vel'].

**Comment by sunghowoo** [comment]
Sorry for the late response. Please refer to this issue to help resolve your problem https://github.com/ROBOTIS-GIT/turtlebot3_manipulation/issues/71
