### ISSUE TITLE
[Simulation, Humble] Joint 'gripper_right_joint_mimic' not found in model 'turtlebot3_manipulation'

### ISSUE THREAD

**Issue by goekce** [ROBOTIS-GIT/turtlebot3_manipulation#66]
I want to simulate TB3-manipulation and followed the Humble instructions. I used:
```
ros2 launch turtlebot3_manipulation_bringup gazebo.launch.py
```
If I additionally:
```
ros2 launch turtlebot3_manipulation_moveit_config servo.launch.py
```

Then I get lot of: 
```
[moveit_robot_model.robot_model]: Joint 'gripper_right_joint_mimic' not found in model 'turtlebot3_manipulation'
```

I can move the arm using `_teleop` however the control buttons seem to be wrongly mapped. For example pressing `joint1+` and then `joint1-` does not return the arm to the original position.

Is this a bug or feature?

**Comment by goekce** [comment]
Probably related to https://github.com/ros-controls/gazebo_ros2_control/issues/173

**Comment by goekce** [comment]
https://github.com/ROBOTIS-GIT/turtlebot3_manipulation/blob/3baa265d0f4843955ed77716be6f88b71689d7a1/turtlebot3_manipulation_description/urdf/open_manipulator_x.urdf.xacro#L210

<s>`gripper_right_joint` => `gripper_right_joint_mimic` gets rid of the errors. I can create a PR if a maintainer acknowledges that this is the right fix. </s> (Update: see my next comment below)

Regarding the teleop issue: The described behavior still exists after the fix. Probably another issue.

**Comment by goekce** [comment]
My workaround led to a static right grip in Gazebo, so I added a dummy joint like shown in https://github.com/ros-controls/gazebo_ros2_control/issues/173:

```xml
    <joint name="${prefix}gripper_right_joint_mimic" type="fixed">
      <parent link="${prefix}link5" />
      <child link="dummy_mimic_fix" />
    </joint>
    <link name="dummy_mimic_fix"/>
```

Also related: https://github.com/ros-controls/gz_ros2_control/issues/96. Probably better to wait for the resolution of this issue.

The source of the error is explained here in detail: https://robotics.stackexchange.com/questions/25107/ros2-moveit-cant-find-mimic-joint

**Comment by chengke-codes** [comment]
Thank @goekce so much for the solution. For anyone need help with this issue

To edit `turtlebot3_manipulation/turtlebot3_manipulation_description/urdf/open_manipulator_x.urdf.xacro`

```xml
<joint name="${prefix}gripper_right_joint" type="prismatic">
   ...
</joint>
<joint name="${prefix}gripper_right_joint_mimic" type="fixed">
  <parent link="${prefix}link5" />
  <child link="dummy_mimic_fix" />
</joint>
<link name="dummy_mimic_fix"/>
```

**Comment by ArpanROS** [comment]
I am also facing the same issue.
![error](https://github.com/user-attachments/assets/69ec5087-cb12-44bc-b896-5cc4298295f1)

**Comment by ArpanROS** [comment]
https://github.com/ArpanROS/ros2.git

This is the git link


Can any one just let me know from which file this error is coming?

**Comment by sunghowoo** [comment]
It seems that this issue has already been resolved above, so I will go ahead and close it.
